# Generated by Django 3.0.5 on 2020-04-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=50, verbose_name='name')),
                ('v_img_no', models.CharField(max_length=50, verbose_name='image_number')),
                ('v_date', models.DateTimeField(verbose_name='Voted at')),
            ],
            options={
                'verbose_name': 'vote_data',
                'verbose_name_plural': 'vote_datas',
            },
        ),
    ]
