# Generated by Django 3.0.5 on 2020-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talesbylight', '0002_auto_20200423_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votedata',
            name='v_img_no',
            field=models.IntegerField(verbose_name='image_number'),
        ),
    ]
